### ISSUE TITLE
Notification delay handling

### ISSUE THREAD

**Issue by rlewan** [wojciechh-kainos/tdp-recruitment#114]
Currently the notification delay is configured via an explicit value in all places, e.g.:

`
Notification.error({message: "Something went wrong with your request." , delay: 3500});
`

Additionally, the delay value varies from place to place.

We should unify notification delay handling by extracting it as a constant/configuration variable.

**Comment by dawidk-kainos** [comment]
I suggest making it
Notification.error("Something went wrong with your request.");
Default time can be set in NotificationProvider.

**Comment by RogowskaMalgorzata** [comment]
Done with Provider
