### ISSUE TITLE
Test for SlotsSerializer to show changes in Slots class

### ISSUE THREAD

**Issue by scyganska** [wojciechh-kainos/tdp-recruitment#38]
When Slots class is changed developer should be reminded to update SlotsSerializer.

**Comment by rlewan** [comment]
Is this issue still valid?

**Comment by RogowskaMalgorzata** [comment]
It is, but it's a problem to create test that checks if both Slot class and Slot Serializer have the same fields.

**Comment by rlewan** [comment]
Have you tried Java Reflection API for that?

**Comment by drauf** [comment]
[This might help](http://stackoverflow.com/questions/16295949/get-all-fields-even-private-and-inherited-from-class).

**Comment by RogowskaMalgorzata** [comment]
The problem is with serialized fields, because they are not class fields, but still I can try something :)
